Repository dynawo/dynaflow-launcher, pull requests merged in 2022-01, with the labels that each got.

#257 #256 update svarc lib following OS 1897
  sources/Outputs/src/Dyd.cpp
  sources/Outputs/src/Par.cpp
  tests/outputs/reference/TestDyd/TestDyd.dyd
  tests/outputs/reference/TestPar/TestPar.par
Labels: enhancement

#265 #264 Remove useless connectors (OS 2063)
  sources/Outputs/src/Dyd.cpp
  tests/outputs/reference/TestDyd/TestDyd.dyd
  tests/outputs/reference/TestDydDynModel/TestDydDynModel.dyd
  tests/outputs/reference/TestDydHvdc/TestDydHvdc.dyd
  tests/outputs/reference/TestDydRemote/TestDydRemote.dyd
  tests/outputs/reference/TestDydSVarC/TestDydSVarC.dyd
Labels: enhancement

#267 #260 Fix rights installation of dynawo and dyn-algo for distrib.
  CMakeLists.txt
Labels: bug

#278 #272 Add workflow_dispatch to nightly to be able to trigger job manua…
  .github/workflows/nightly.yml
Labels: DevOps

#284 #273 Fix name of dynawo and dyn-algo releases used in release workflow.
  .github/workflows/release.yml
Labels: DevOps

#286 #285 Fix dynawo-algorithms call following 160 in it.
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: DevOps

#281 #272 Build shared library version instead of static one.
  .github/workflows/nightly-release.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: DevOps

#290 #273 Fix version output in stderr and not stdout.
  .github/workflows/release.yml
Labels: DevOps

#292 #291 Fix runtime for shared library version build.
  scripts/envDFL.sh
Labels: bug

#293 #280 remove results folder before running tests again
  .gitignore
  cmake/TestMain.cmake
  cmake/TestMainSA.cmake
  scripts/checkContingencies.py
  scripts/diff.py
  scripts/diffContingencies.py
  scripts/envDFL.sh
  tests/Tests.h
  tests/main/res/config_distant_regulation.json
  tests/main/res/config_hvdc.json
  tests/main/res/config_hvdc_HvdcPQProp.json
  tests/main/res/config_hvdc_HvdcPQPropDangling.json
  tests/main/res/config_hvdc_HvdcPQPropDangling_diagrams.json
  tests/main/res/config_hvdc_HvdcPQPropSwitch.json
  tests/main/res/config_hvdc_HvdcPQProp_diagrams.json
  tests/main/res/config_hvdc_HvdcPVDangling_HvdcPTanPhiDangling.json
  tests/main/res/config_hvdc_HvdcPVDangling_HvdcPTanPhiDangling_diagrams.json
  tests/main/res/config_hvdc_HvdcPV_HvdcPTanPhi.json
  tests/main/res/config_hvdc_HvdcPV_HvdcPTanPhi_diagrams.json
  tests/main/res/config_hvdc_dangling.json
  tests/main/res/config_hvdc_diagrams.json
  tests/main/res/config_hvdc_line_normal.json
  tests/main/res/config_launch.json
  tests/main/res/config_launch_P.json
  tests/main/res/config_launch_fail_generators.json
  tests/main/res/config_launch_infinite.json
  tests/main/res/config_launch_slack.json
  tests/main/res/config_node_breaker.json
  tests/main/res/config_phase_shifter.json
  tests/main/res/config_special_characters.json
  tests/main_sa/res/config_launch.json
  tests/outputs/TestDiagram.cpp
  tests/outputs/TestDyd.cpp
  tests/outputs/TestDydEvent.cpp
  tests/outputs/TestPar.cpp
  tests/outputs/TestParEvent.cpp
  tests/outputs/reference/TestPar/TestPar.par
  tests/outputs/reference/TestParDynModel/TestParDynModel.par
  tests/outputs/reference/TestParHvdc/TestParHvdc.par
  tests/outputs/reference/TestParRemote/TestParRemote.par
Labels: bug
