Repository dynawo/dynaflow-launcher, pull requests merged in 2023-07, with the labels that each got.

#683 #682 Fix error with GTest:Main target not a library.
  .gitignore
  tests/CMakeLists.txt
Labels: bug

#675 #449 Publish nightly doc
  .github/workflows/nightly-release.yml
Labels: documentation, DevOps

#685 #668 replace action with javascript
  .github/workflows/nightly-release.yml
Labels: DevOps

#688 #687 use lowercase 'v' for release version
  .github/workflows/ci.yml
  .github/workflows/nightly-release.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: DevOps

#691 #690 Start nightlies on repository dispatch
  .github/workflows/nightly.yml
Labels: DevOps
