Repository dynawo/dynaflow-launcher, pull requests merged in 2023-01, with the labels that each got.

#530 #529 Update tests for slackTerminal iidm extension following 2687 fro…
  tests/main/reference/launch_slack/outputIIDM.xml
  tests/main/res/TestIIDM_launch_slack.iidm
Labels: bug

#542 #541 Add centos7 distribution generation.
  .github/workflows/release.yml
Labels: DevOps

#543 #539 Fix workflow curl calls and add token.
  .github/workflows/ci.yml
  .github/workflows/nightly-release.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/tools.sh
Labels: DevOps

#547 380 nightly workflow v14
  .github/workflows/ci.yml
  .github/workflows/nightly-release.yml
Labels: DevOps

#553 #539 Update api to use token in workflow and avoid github limite rate.
  .github/workflows/ci.yml
  .github/workflows/nightly-release.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/tools.sh
Labels: DevOps

#554 #539 Update api to use token in workflow and avoid github limite rate.
  .github/workflows/ci.yml
  .github/workflows/nightly-release.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/tools.sh
Labels: DevOps

#565 #555 Update following OS 2737
  tests/main/res/assembling_phase_shifter.xml
  tests/main/res/setting_phase_shifter.xml
Labels: Update from external ticket

#556 #555 Update following OS 2737
  tests/main/res/assembling_phase_shifter.xml
  tests/main/res/setting_phase_shifter.xml
Labels: Update from external ticket
